// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.applePicker.subsystems;

import java.awt.Robot;

import org.usfirst.frc5265.applePicker.RobotMap;
import org.usfirst.frc5265.applePicker.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class jakeBase extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon jakefrontright = RobotMap.jakeBasejakefrontright;
    private final CANTalon jakerearright = RobotMap.jakeBasejakerearright;
    private final CANTalon jakefrontleft = RobotMap.jakeBasejakefrontleft;
    private final CANTalon jakerearleft = RobotMap.jakeBasejakerearleft;
    private final RobotDrive stagMotor = RobotMap.jakeBasejakeRobotDrive;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public double returnEncoderValue () {
    	return jakefrontright.getEncPosition();
    }
    
    public void zeroEncoderValue () {
    	jakefrontright.setEncPosition(0);    	
    }
    
    public void setEncoderDistance(double distance){
    	jakefrontright.setPosition(distance);
    }
    
    public void jakeTank(double leftspeed,double rightspeed){
    	stagMotor.tankDrive(leftspeed, rightspeed);
    }
    
}

