// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.applePicker;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon jakeBasejakerearleft;
    public static CANTalon jakeBasejakefrontleft;
    public static CANTalon jakeBasejakerearright;
    public static CANTalon jakeBasejakefrontright;
    public static RobotDrive jakeBasejakeRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        jakeBasejakerearleft = new CANTalon(1);
        LiveWindow.addActuator("jakeBase", "jakerearleft", jakeBasejakerearleft);
        
        jakeBasejakefrontleft = new CANTalon(0);
        LiveWindow.addActuator("jakeBase", "jakefrontleft", jakeBasejakefrontleft);
        
        jakeBasejakerearright = new CANTalon(3);
        LiveWindow.addActuator("jakeBase", "jakerearright", jakeBasejakerearright);
        
        jakeBasejakefrontright = new CANTalon(2);
        LiveWindow.addActuator("jakeBase", "jakefrontright", jakeBasejakefrontright);
        
        jakeBasejakeRobotDrive = new RobotDrive(jakeBasejakefrontleft, jakeBasejakerearleft,
              jakeBasejakefrontright, jakeBasejakerearright);
        
        jakeBasejakeRobotDrive.setSafetyEnabled(true);
        jakeBasejakeRobotDrive.setExpiration(0.1);
        jakeBasejakeRobotDrive.setSensitivity(0.5);
        jakeBasejakeRobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
